### PR TITLE
Fix up file menu names and order to better match UI standards

### PR DESCRIPTION
**Pull request by ghutchis**

### CODE REVIEW

**Comment by ghutchis** [comment]
I'm going to work on a deeper patch that will adopt a mainwindow.ui for the menus and rip out a bunch of code, but this should be merged before the next release.

**Comment by cryos** [comment]
I see two exports, one populated and another empty one. I haven't dug into why, but it would be good to figure that out before merging this patch.

**Comment by ghutchis** [comment]
That new change should do it - duplication of "Export" vs "&Export" from a plugin.

**Comment by cryos** [comment]
Looks good here

**Pull request merged**
