### PR TITLE
 added the functions openFile and saveGraphic to connection class

### PR DESCRIPTION
**Pull request by adityaomar3**
Refactored the code as asked, added the functions openFile() and saveGraphic() to connection class

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ghutchis** [comment]
It's a nice start. 

It would be great to refactor the entire `connection` class so that the methods take arguments and use Pythonic method names, like:

`open_file(filename)`
`save_graphic(filename)`

There is already an `avogadro` PyPI module, and it would be nice to include the `connection` into that.

A few sub-tasks:
- Error detection in `__init__` if the socket cannot be created.
- Merge the current `send_message` and `receive_message` methods (which handle the low-level interaction with the connection) into the `_json` methods.
- Create new "high level" `send_message(method, params = {})` method which formats the JSON template to minimize code duplication:
```
{
    "jsonrpc": "2.0",
    "id": 0,
    "method": method,
    "params": params,
}
```
- Add methods for all the current RPC methods:
    - kill
    - openFile(filename)
    - loadMolecule(string)
    - saveGraphic(filename)
    - exportFile(filename)

Does that make sense?

**Comment by adityaomar3** [comment]
Also if you can help me with the functions loadMolecule and exportFile will do, so that I can implement them

**Comment by adityaomar3** [comment]
oops! I think I pressed something wrong in my git

**Comment by adityaomar3** [comment]
closing this pull request, I think I messed up with my git, will open a new one for the changes

**Pull request closed without merging**
