### PR TITLE
Update avogadro2.desktop

### PR DESCRIPTION
**Pull request by ovari**
Signed-off-by: Óvári Óvári ovari123@zoho.com

https://github.com/OpenChemistry/avogadroapp/issues/217#issuecomment-916997742

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ghutchis** [comment]
Thanks - can you take care of the `git` signoff?
https://github.com/OpenChemistry/avogadroapp/pull/222/checks?check_run_id=3572556071
`git commit --amend --no-edit --signoff`

We don't ask for copyright assignment, but we do appreciate having full names.

I'm going through the comments - I'll probably get a bunch of them today and some tomorrow.

**Comment by ovari** [comment]
> Thanks - can you take care of the `git` signoff?
> https://github.com/OpenChemistry/avogadroapp/pull/222/checks?check_run_id=3572556071
> `git commit --amend --no-edit --signoff`
> 
> We don't ask for copyright assignment, but we do appreciate having full names.

How can this be done using a web-browser interface?

Another solution is for you to add any suggested strings as neither recognition nor copyright is required. If so, please advise when you have added the suggested strings to enable this merge request and fork to be deleted.

Our purpose is nothing more than to enable people to use your software in their native language.

Thank you for your understanding.

**Comment by ovari** [comment]
> I'm going through the comments - I'll probably get a bunch of them today and some tomorrow.

Thank you

**Comment by ovari** [comment]
Signed-off-by: Óvári ovari123@zoho.com

Add the first line in this comment to the first line in the description. Does that take care of the git signoff?

Thank you

**Comment by ovari** [comment]
@kevinsmia1939 can you please merge this commit? Thank you

**Comment by kevinsmia1939** [comment]
> @kevinsmia1939 can you please merge this commit? Thank you

I don't have the permission to merge this.

**Comment by ghutchis** [comment]
As I mentioned above:
> We don't ask for copyright assignment, but we do appreciate having full names.

That is, I'll need more than "Óvári" for a sign-off, thanks.

**Comment by ovari** [comment]
> We don't ask for copyright assignment, but we do appreciate having full names.

Anyone can have the copyright assignment.

> That is, I'll need more than "Óvári" for a sign-off, thanks.

"Óvári" is the full name. If it can be signed-off with just that unfortunately this merge request will need to be abandoned.

As this commit is just text, anyone is welcome to create a merge request with these strings.

Thank you

**Pull request closed without merging**
