### PR TITLE
Add flatpak infrastructure

### PR DESCRIPTION
**Pull request by jakobjakobson13**
This could be the beginning of the fix for #97 even further work has to be done.

Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by ghutchis** [comment]
Thanks, that's a big help. I have a few things today, but I hope to look at it on Saturday or Sunday.

**Comment by jakobjakobson13** [comment]
I made some progress and reached the error
```========================================================================
Building module avogadrolib in /__w/avogadroapp/avogadroapp/.flatpak-builder/build/avogadrolib-1
========================================================================
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Debug' as none was specified.
-- Performing Test HAVE_GCC_ERROR_RETURN_TYPE
-- Performing Test HAVE_GCC_ERROR_RETURN_TYPE - Success
-- Found Git: /usr/bin/git (found version "2.26.2") 
-- Could not use git to determine source version, using version 1.93.0
-- Found Eigen3: /app/include/eigen3 (Required is at least version "2.91.0") 
CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (SPGLIB)
  does not match the name of the calling package (Spglib).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindSpglib.cmake:15 (find_package_handle_standard_args)
  avogadro/core/CMakeLists.txt:7 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find SPGLIB (missing: SPGLIB_LIBRARY) 
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found MMTF: /app/include  
CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindOpenGL.cmake:305 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  avogadro/rendering/CMakeLists.txt:6 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found GLEW: /app/include  
-- Found PythonInterp: /app/bin/python2 (found suitable version "2.7.18", minimum required is "2") 
Avogadro Generators not found at /run/build/avogadrolib/../avogadrogenerators!
CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (LIBARCHIVE)
  does not match the name of the calling package (LibArchive).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindLibArchive.cmake:17 (find_package_handle_standard_args)
  avogadro/qtplugins/plugindownloader/CMakeLists.txt:3 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found LIBARCHIVE: /usr/include  
msym include dir /app/lib/cmake/libmsym/../../../include
CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindOpenGL.cmake:305 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  avogadro/qtplugins/overlayaxes/CMakeLists.txt:3 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SPGLIB_LIBRARY (ADVANCED)
    linked by target "AvogadroCore" in directory /run/build/avogadrolib/avogadro/core

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Error: module avogadrolib: Child process exited with code 1
```

Can someone explain the error message? Without the patch I introduced, I don't even get to the `avogadrolib` module as `molequeue` fails.

**Comment by ghutchis** [comment]
(sigh) Molequeue... okay, I'll see what's going on there..

**Comment by ghutchis** [comment]
can we grab from git instead of the releases, e.g.

openchemistry/
.. avogadroapp (latest)
.. avogadrolibs (latest)
.. molequeue (latest)

This version of the manifest probably works for releases, but I think the build will go much better if you build from the openchemistry repo, e.g.

https://github.com/OpenChemistry/avogadrolibs/blob/master/.github/workflows/build_cmake.yml
```
    - name: Checkout openchemistry
      uses: actions/checkout@v2
      with:
        repository: openchemistry/openchemistry
        submodules: recursive

    - name: Checkout avogadroapp
      uses: actions/checkout@v2
      with:
        repository: openchemistry/avogadroapp
        path: avogadroapp

    - name: Checkout avogadrolibs
      uses: actions/checkout@v2
      with:
        path: avogadrolibs
```

**Comment by ghutchis** [comment]
The problem is that the flags to find SPGLIB aren't set. I suspect if you use the git `HEAD` for each project, this should solve it.

**Comment by jakobjakobson13** [comment]
Hm, how can use the git `HEAD`. I tried mirroring your git repositories but apparently that does not work. And the further options I have are limited, see [https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html#flatpak-builder](https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html#flatpak-builder).

**Comment by kevinsmia1939** [comment]
Hi,

I also tried to build Avogadro Flatpak.
I got pass molequeue and failed at avogadrolibs.
https://github.com/kevinsmia1939/flathub/tree/org.openchemistry.Avogadro2

I have issue with spglib not being detect properly.
https://github.com/OpenChemistry/avogadrolibs/issues/531

**Comment by ghutchis** [comment]
I'm closing in favor of #132 - but thank you a *lot* for your help getting this started.

**Pull request closed without merging**
