### PR TITLE
Fix menubuilder

### PR DESCRIPTION
**Pull request by ghutchis**
MenuBuilder will now replace existing menu items or submenus,
preserving menu order. For example, regardless of the order
loaded, Import will always appear before Export as defined
in mainwindow.ui.

Moreover, menu items will *not* be sorted alphabetically.
Plugin authors may have a reason for a particular order of items.
MenuBuilder should respect that:
(e.g., cut, copy, paste, clear - not clear, copy, cut, paste)

Probably still some bugs also.

### CODE REVIEW

**Comment by cryos** [comment]
I was just taking a look, and this doesn't work for me, testing on Linux with Qt 5.7.1. I end up with File, Edit, View, Build, Select, Extensions, Settings, Help, Crystal, Extensions, Quantum and Select as top level menu items here. The first select is empty, I am wondering what I should see. I can do a little digging. I see odd behavior on the select command branch, but I think it might be because it relies upon changes here?

**Comment by ghutchis** [comment]
I have been testing those branches together, although this was done first. The usual problem with menus is &Select vs. Select, etc.

**Comment by ghutchis** [comment]
I'm going to add back the Help menu as a plugin.

**Comment by cryos** [comment]
I can dig into this, but am still seeing issues on Linux with my builds. It may be the way you are trying to do string matching on QActions when some OS styles can insert shortcuts. Top level is still odd here - File, Edit, View, Build (empty), Select (empty), Extensions (empty), Crystal, Extensions, Quantum, Select, Help.

**Comment by ghutchis** [comment]
I *think* that should do it?

**Comment by cryos** [comment]
Looks great Geoff, thanks for persevering. I will try to get a Windows build I can test soon, but I think it will work as expected there too.

**Pull request merged**
